import { useApp } from '../store/AppContext';
import { categoryTotals } from '../utils/month';
import { formatCurrency } from '../utils/format';
import PageHeader from '../components/PageHeader';
import { ArrowUpRight, ReceiptText, Coffee, Car, ShoppingBag, House, Shapes, Heart, Film } from 'lucide-react';
const icons={Food:Coffee,Transport:Car,Shopping:ShoppingBag,Bills:House,Housing:House,Medical:Heart,Health:Heart,Entertainment:Film};
export default function Dashboard() {
    const { user, expenses, monthlyExpenses, setCurrentScreen }=useApp();
    const bills=monthlyExpenses.filter(e=>e.category!=='Income');
    const spent=bills.reduce((sum,e)=>sum+Number(e.amount),0);
    const income=monthlyExpenses.filter(e=>e.category==='Income').reduce((sum,e)=>sum+Number(e.amount),0);
    const budget=Number(user.budget)||0, remaining=budget-spent;
    const breakdown=categoryTotals(monthlyExpenses);
    const days=Array.from({length:7},(_,i)=>{const date=new Date();date.setDate(date.getDate()-6+i);return {date,label:date.toLocaleDateString('en-IN',{weekday:'short'}),total:expenses.filter(e=>e.category!=='Income'&&new Date(e.date).toDateString()===date.toDateString()).reduce((s,e)=>s+Number(e.amount),0)};});
    const max=Math.max(...days.map(d=>d.total),1);
    const month=new Date().toLocaleDateString('en-IN',{month:'long',year:'numeric'});
    return <><PageHeader title="Dashboard" subtitle={`Your personal spending · ${month}`} onBack={()=>setCurrentScreen('home')} actions={<button aria-label="Transactions" className="button-secondary" onClick={()=>setCurrentScreen('logs')}><ReceiptText size={18}/><span>Transactions</span></button>}/>
        <div className="polished-content"><div className="metric-grid"><div className="metric-card featured"><span>Spent this month</span><strong>Rs. {formatCurrency(spent)}</strong><small>{bills.length} expense{bills.length===1?'':'s'} recorded</small></div><div className="metric-card"><span>{budget ? remaining<0?'Over budget':'Budget remaining':'Monthly budget'}</span><strong>{budget ? `Rs. ${formatCurrency(Math.abs(remaining))}` : 'Not set'}</strong><small>{budget?`of Rs. ${formatCurrency(budget)} planned`:'Set a limit in Profile'}</small></div><div className="metric-card"><span>Income logged</span><strong>Rs. {formatCurrency(income)}</strong><small>This calendar month</small></div></div>
        <div className="analytics-grid"><section className="surface-card"><div className="surface-title"><h2>Where it went</h2><span>{breakdown.length} categories</span></div>{breakdown.length ? breakdown.map(({category,total})=>{const Icon=icons[category]||Shapes;return <div className="category-item" key={category}><div className="category-symbol"><Icon size={18}/></div><div><h3>{category}</h3><div className="category-bar"><span style={{width:`${spent ? total/spent*100:0}%`}}/></div></div><div style={{textAlign:'right'}}><strong>Rs. {formatCurrency(total)}</strong><small>{spent?Math.round(total/spent*100):0}% of spending</small></div></div>;}) : <p className="empty-note">Your first expense will start the story. Categories appear here as you log.</p>}</section>
        <section className="surface-card"><div className="surface-title"><h2>Your monthly pace</h2><span>{budget?'Budget overview':'No limit set'}</span></div><div className="budget-figure">{budget?`${Math.round(spent/budget*100)}%`:'—'}<span>{budget?'of your monthly budget used':'Set a budget to see your pace'}</span></div><div className="budget-track"><span style={{width:`${budget?Math.min(100,spent/budget*100):0}%`,background:remaining<0&&budget?'#bd7251':undefined}}/></div><div className="budget-caption"><span>Rs. {formatCurrency(spent)} spent</span><span>{budget?`Rs. ${formatCurrency(budget)} limit`:'No spending limit'}</span></div><div className="insight-callout">{!budget?'A monthly limit helps you see how much room you have left. You can add one in Profile.':remaining<0?`You’re Rs. ${formatCurrency(-remaining)} over your monthly limit. Your full history can help you decide what to adjust.`:`You have Rs. ${formatCurrency(remaining)} of your monthly budget left. Your stats start fresh next month; your history stays.`}</div><button className="text-link" onClick={()=>setCurrentScreen('profile')}>Manage your budget <ArrowUpRight size={15}/></button></section>
        <section className="surface-card analytics-wide"><div className="surface-title"><h2>The last seven days</h2><span>Rs. {formatCurrency(days.reduce((s,d)=>s+d.total,0))} spent</span></div><div className="weekly-bars">{days.map((day,i)=><div className="weekly-day" key={day.label}><span className="weekly-value">Rs. {formatCurrency(day.total)}</span><div className="weekly-bar-track"><div className={i===6?'today':''} style={{height:`${day.total?Math.max(3,day.total/max*100):0}%`}}/></div><span className="weekly-label">{i===6?'Today':day.label}</span></div>)}</div><p className="field-help" style={{marginBottom:0}}>Personal expenses only. Income and group bill totals aren’t counted as spending here.</p></section></div>
        </div></>;
}
