import { useMemo, useState } from 'react';
import { useApp } from '../store/AppContext';
import EditExpenseSheet from '../components/EditExpenseSheet';
import BottomSheet from '../components/BottomSheet';
import PageHeader from '../components/PageHeader';
import { formatCurrency } from '../utils/format';
import { monthKey } from '../utils/month';
import { Search, ReceiptText, Pencil, Trash2, ArrowDownLeft, X, Plus } from 'lucide-react';
export default function TransactionLogs() {
    const { expenses, setCurrentScreen, deleteExpense, updateExpense }=useApp();
    const [search,setSearch]=useState(''),[category,setCategory]=useState('All'),[period,setPeriod]=useState('All time');
    const [editing,setEditing]=useState(null),[deleting,setDeleting]=useState(null),[busy,setBusy]=useState(false);
    const categories=['All',...new Set(expenses.map(e=>e.category).filter(Boolean))];
    const filtered=useMemo(()=>expenses.filter(e=>(category==='All'||e.category===category)&&(period==='All time'||monthKey(new Date(e.date))===monthKey())&&`${e.description||''} ${e.amount} ${e.category}`.toLowerCase().includes(search.toLowerCase().trim())).sort((a,b)=>new Date(b.date)-new Date(a.date)),[expenses,search,category,period]);
    const spent=filtered.filter(e=>e.category!=='Income').reduce((s,e)=>s+Number(e.amount),0),income=filtered.filter(e=>e.category==='Income').reduce((s,e)=>s+Number(e.amount),0);
    const months=filtered.reduce((groups,e)=>{const key=new Date(e.date).toLocaleDateString('en-IN',{month:'long',year:'numeric'});(groups[key]||=[]).push(e);return groups;},{});
    return <><PageHeader title="Transactions" subtitle="Every little expense. All in one place." onBack={()=>setCurrentScreen('home')} actions={<button aria-label="Add in Wallet" className="button-secondary" onClick={()=>setCurrentScreen('home')}><Plus size={18}/><span>Add in Wallet</span></button>}/><div className="polished-content">
        <div className="metric-grid"><div className="metric-card featured"><span>Expenses</span><strong>Rs. {formatCurrency(spent)}</strong><small>For the selected filters</small></div><div className="metric-card"><span>Income</span><strong>Rs. {formatCurrency(income)}</strong><small>For the selected filters</small></div><div className="metric-card"><span>Entries</span><strong>{filtered.length}</strong><small>{period}</small></div></div>
        <div className="transaction-toolbar"><div className="search-field"><Search size={18}/><input aria-label="Search transactions" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search a name, amount or category"/>{search&&<button className="clear-search" aria-label="Clear search" onClick={()=>setSearch('')}><X size={16}/></button>}</div><div className="filter-pills period-filters" role="group" aria-label="Time period">{['All time','This month'].map(label=><button className={period===label?'active':''} aria-pressed={period===label} onClick={()=>setPeriod(label)} key={label}>{label}</button>)}</div><div className="filter-pills category-filters" role="group" aria-label="Categories">{categories.map(label=><button className={category===label?'active':''} aria-pressed={category===label} onClick={()=>setCategory(label)} key={label}>{label}</button>)}</div></div>
        {!filtered.length&&<div className="empty-state"><ReceiptText size={32}/><h2>{expenses.length?'No matches this time.':'Your wallet story starts here.'}</h2><p>{expenses.length?'Try another search or clear your filters.':'Log your first personal expense in Wallet. You’ll find it here, ready to review or edit.'}</p><button className="button-secondary" onClick={()=>{if(expenses.length){setSearch('');setCategory('All');setPeriod('All time');}else setCurrentScreen('home');}}>{expenses.length?'Clear filters':'Go to Wallet'}</button></div>}
        {Object.entries(months).map(([month,items])=><section className="transaction-month" key={month}><div className="transaction-month-heading"><h2>{month}</h2><span>Rs. {formatCurrency(items.filter(e=>e.category!=='Income').reduce((s,e)=>s+Number(e.amount),0))} spent</span></div><div className="transaction-list">{items.map(e=><article className="transaction-row" key={e.id}><div className="category-symbol">{e.category==='Income'?<ArrowDownLeft size={18}/>:<ReceiptText size={18}/>}</div><div><div className="transaction-name">{e.description||'Expense'}</div><div className="transaction-meta">{e.category} · {new Date(e.date).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</div></div><strong className={`transaction-amount${e.category==='Income'?' income':''}`}>{e.category==='Income'?'+':''}Rs. {formatCurrency(e.amount)}</strong><div className="transaction-tools"><button aria-label={`Edit ${e.description||'expense'}`} onClick={()=>setEditing(e)}><Pencil size={15}/></button><button aria-label={`Delete ${e.description||'expense'}`} onClick={()=>setDeleting(e)}><Trash2 size={15}/></button></div></article>)}</div></section>)}
    </div><EditExpenseSheet isOpen={!!editing} onClose={()=>setEditing(null)} expense={editing} onSave={updates=>updateExpense(editing.id,updates)}/><BottomSheet isOpen={!!deleting} onClose={()=>{if(!busy)setDeleting(null);}} title="Delete this entry?"><p className="field-help">{deleting?.description} · Rs. {formatCurrency(deleting?.amount||0)}. This removes the entry from your Wallet and updates your totals.</p><div style={{display:'flex',gap:10}}><button disabled={busy} className="button-secondary" onClick={()=>setDeleting(null)}>Keep entry</button><button disabled={busy} className="button-primary" onClick={async()=>{setBusy(true);try{if (await deleteExpense(deleting.id)) setDeleting(null);}finally{setBusy(false);}}}>{busy?'Deleting…':'Delete entry'}</button></div></BottomSheet></>;
}
